### ISSUE TITLE
Lecture 6

### ISSUE THREAD

**Issue by annwhoorma** [SergeiSa/Linear-Control-Slides-Spring-2020#15]
That's a third slide from lecture 6. Second line defines the system we will be working with.
Suggestion is to show that _x_ and _u_ depend on time (_t_). It is not obvious (wasn't for me) and if we write **_x'(t) = f( x(t), u(t) )_** then the following initial condition _x(0)_ makes more sense.
![image](https://user-images.githubusercontent.com/34862867/79113459-a0346000-7d89-11ea-8bfa-6783fc6c0cd9.png)

**Comment by SergeiSa** [comment]
That is a very good comment, especially because it kinda touches on the overall notation issue with this slide. for example, in the first formula u is a variable, with we think of as dependent on time, u = u(t). Next expression has u as a *policy*, in other words, as one of many possible functions. In this sense, J does not depend on the value of u at a given point in time, but on the entirety of u. 

I will try to think about how to fix this issue without making the slide a notational horror. Thank you for bringing it to attention!

**Comment by annwhoorma** [comment]
> Next expression has u as a _policy_, in other words, as one of many possible functions. In this sense, J does not depend on the value of u at a given point in time, but on the entirety of u.

I'm not sure I understood the part about _u as a policy_. How to know, when some variable is a _policy_ and when it is a _variable_?

> J does not depend on the value of u at a given point in time, but on the entirety of u.

But what is the difference? _J_ depends on _u_ in general - I get, but still, if we want to define _J_ at some _t0_, we need to know _u_ at _t0_.

Difference between policy and variable seems too abstract to me

**Comment by SergeiSa** [comment]
When I said policy, I meant, u as a function. You can choose u=-Kx, or u = cot(t), or u = 0.7, all are different policies. Even though for some value of t all three can be equal.

J does not depend on time, it is an integral over time, is the important part here. You can see its definition on other slides. 

I would suggest you to look through http://underactuated.mit.edu/lqr.html and other material in that textbook. I will think about how to make these slides more clear too

**Comment by annwhoorma** [comment]
Yes, now I understood. 
Thanks!
